### ISSUE TITLE
RFE: Improved artist/non-technical user experience

### ISSUE THREAD

**Issue by BrianHanke** [AcademySoftwareFoundation/OpenColorIO#1385] opened 2021-04-21 23:26 UTC
I've been following OCIO for a while now, trying to learn as much as I can about how it works and how best to use it. I'm a solo artist using Houdini, Substance Painter, Nuke, Maya and Photoshop. The core of OCIO is obviously extremely solid and powerful. But I do find that the end user experience, especially for non-technical users, is often complicated and confusing.

I ended up creating my own config that attempts to streamline things. It seems to work fine, but it's asking a lot to expect artists to do this and honestly I'm still not sure I did it "right." It looks fine across various apps, but given the complexity of the topic just looking right may not mean working right!

I think most of the annoyances could be solved by creating an official simplified default config. If you go with each app on its own they all do wildly different things. Right now we have Maya 2022 which greets you with a default of "ACES 1.0 SDR-video," Houdini which has no defaults, Photoshop which only works with a somewhat obscure 3rd party plugin, and Nuke which comes with its own config that doesn't include ACEScg. It's kind of a Wild West.

It could be argued that it's up to each developer to make their own configs, but I think that's asking for trouble as each go their own way. If OCIO provided a recommended default, with standardized terminology, then developers could just implement that and let more advanced users/big studios install more complicated configs that do what they need.

As an artist I would LOVE to open up Maya, work in ACEScg with sRGB textures, check my work using sRGB view, render to linear EXR, bring that into Nuke, pick linear EXR there, set that view transform to sRGB and be ready to roll. The current system provides many speed bumps: Maya doesn't have simple sRGB out, it has SDR-video. Is that the same? I guess so. But it's not clear and it makes you wonder. Then I bring my render into Nuke and maybe it doesn't look the same as in Maya. I go to pick another color space and I have 10 different choices all with various combinations of linear and sRGB and raw in the name and that's another speed bump. In the end it works out, but it could be so much smoother.

Having universal terminology and a core set of common defaults would be a huge benefit to many users. Thanks for your attention!

**Comment by doug-walker** [comment] 2022-04-06 03:16
Closing this as a duplicate of #1621.

**Closed by doug-walker** 2022-04-06 03:16 UTC
