### ISSUE TITLE
Impossible to build against system/external minizip-ng

### ISSUE THREAD

**Issue by LazyDodo** [AcademySoftwareFoundation/OpenColorIO#1718] opened 2022-11-02 02:19 UTC
the minizip-ng build over [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/share/cmake/modules/Findminizip-ng.cmake#L136) specifies to install the headers in a subfolder called `minizip-ng` however an external build of minizip-ng is unlikely to have this option set as it is non standard. 

The problem arises [here](https://github.com/AcademySoftwareFoundation/OpenColorIO/blob/main/src/OpenColorIO/OCIOZArchive.cpp#L20) where the code blindly assumes this sub folder to exist, which isn't the case unless you let OCIO build minizip.

**Comment by remia** [comment] 2022-11-02 17:41
Also noticed OpenColorIO won't find minizip-ng built with `MZ_COMPAT=ON`, which is the default, because that build a library without the ng suffix. I'm not familiar enough with this library to know if this is expected or not to have that kind of incompatibility.

**Comment by LazyDodo** [comment] 2022-11-02 19:38
ran into that as well, but you can sidestep that by passing ` -Dminizip-ng_LIBRARY=/where/ever/it/lives/blah.a_lib_so`  to your cmake configure invocation for OCIO.

**Comment by kmilos** [comment] 2022-11-15 10:38
See also patches that were necessary for unbundling the MSYS2 OCIO package: https://github.com/msys2/MINGW-packages/tree/master/mingw-w64-opencolorio

**Comment by cedrik-fuoco-adsk** [comment] 2022-11-17 18:35
Hi @kmilos,

Could you provide the steps to reproduce the issue fixed by 0005-Fix-Findminizip-ng.patch? I've tried to build it manually under MSYS2 without that patch (I removed it manually), and it seems to be working correctly.

**Comment by kmilos** [comment] 2022-11-18 08:23
@cedrik-fuoco-adsk You're probably right that `0005-Fix-Findminizip-ng.patch` is not absolutely necessary (btw, the convention is to use the plural `_LIBRARIES` and `_INCLUDE_DIRS` variables, but that's a minor detail), I think it's just the maintainer preferring to do things the "more modern" CMake way...

**Closed** 2022-12-05 22:33 UTC
