### ISSUE TITLE
"Assertion Failed" Crash in Adobe After Effects 2021 (18.0.1 Build 1)/Windows 10

### ISSUE THREAD

**Issue by df-0** [AcademySoftwareFoundation/OpenColorIO#1364] opened 2021-04-09 06:22 UTC
Pasting a copied instance of the effect gives the following error: 

![image](https://user-images.githubusercontent.com/16046786/114136176-34d09000-9902-11eb-9b03-c5267710f92c.png)

You can actually continue to use AE while the error window is there but if you press ignore it exits AE without saving.

Steps to reproduce

1. Open After Effects (I'm using the -m argument to open multiple AE instances, don't know if that's related)
2. Create new composition
3. Create a solid in that composition
4. Add the OCIO utility to that solid
5. copy the effect (from the effect panel)
6. Create a second composition
7. Add a second instance of the solid to the second composition
8. In the effect window, edit->paste or press ctrl+v
9. That should do it!

Video attached: 

https://user-images.githubusercontent.com/16046786/114137583-5468b800-9904-11eb-8ed6-f180de82d39f.mp4

**Comment by hodoulp** [comment] 2021-04-09 15:18
Hi @df-0,

Thanks for reporting the problem to the community.

The description and the steps would let me first contact `After Effects` before reporting a bug to `OpenColorIO`. That's my 2-cents suggestion. If you are still convince that it's an `OpenColorIO` bug, one approach would be to reproduce the problem using one of the `OpenColorIO` command line tool. 

Patrick

**Comment by df-0** [comment] 2021-04-09 15:57
Hi @hodoulp - hmm, you probably know more about it than me - but this doesn't happen with other effects in AE, and the assert message specifically mentions both the OCIO plugin (I'm using this one: https://fnordware.blogspot.com/2012/05/opencolorio-for-after-effects.html) and a Brendan (who seems to be the plugin's author), so it does seem likely that it's related (imho)? 

I've never used the OpenColorIO command line tool, but since this issue is specific to the OCIO plugin in AE I don't see how one could reproduce this problem from the command line? Apologies if I'm posting this in the wrong place - this is the Github the blog post points to so I assumed they were related.

**Comment by EvanAW** [comment] 2021-04-09 22:48
Glancing at the code the error points to, it is trying to reset pre-existing sequence data. It asserts because the sequence data is NUL.  @fnordware any ideas?

**Comment by fnordware** [comment] 2021-04-10 01:33
Yep, this is a bug. AE is sending a callback at a weird time with inputs I'm not expecting (in_data->sequence_data == NULL). I've fixed it in 6df53b613c0f0299f5d36e5aa343e1306f524804.

Also, the release builds shouldn't be throwing assertions (although in this case it was handy), so I fixed that in e3ab745a9eee5de113e1d44a11a07601500f14ff.

I updated my [posted builds](http://fnordware.blogspot.com/2012/05/opencolorio-for-after-effects.html), but it looks like you guys have moved to OCIO version 2.1, so I'll pull the latest changes in and update my builds again soon.

Thanks for the bug report with screen cap!

**Comment by df-0** [comment] 2021-04-10 06:39
Brilliant, thanks guys!

**Comment by hodoulp** [comment] 2021-04-10 12:26
@fnordware The `master` is now dedicated to the next release i.e. 2.1.x while the branch `RB-2.0` is for 2.0.x.

**Comment by hodoulp** [comment] 2021-04-10 12:27
@fnordware, @df-0 Can the issue be closed?

**Comment by EvanAW** [comment] 2021-04-10 13:18
@hodoulp although @fnordware has fixed the issue in a branch on his GitHub and updated the downloads on his blog, shouldn’t this issue stay open until a PR to this, the main repository, lands in master?

**Comment by hodoulp** [comment] 2021-04-10 13:26
> shouldn’t this issue stay open until a PR to this, the main repository, lands in master?

Not clear if that was the intent. But it's better to explicitly ask.
@fnordware Do you plan to back port the fix from your fork in `master` and perhaps, `RB-2.0`?

**Comment by fnordware** [comment] 2021-04-10 16:08
I can do RB-2.0 if you prefer. I guess master is for 2.1, which won't be ready for quite some time?

**Comment by hodoulp** [comment] 2021-04-10 16:48
I suggest that you first create a pull request against `master` and later integrate the change (i.e. `git cherry-pick`) to `RB-2.0` upon TSC approval.

**Comment by df-0** [comment] 2021-04-11 16:04
I've just tested it again with the latest download from @fnordware's blog, and it certainly appears to have fixed the problem - when I repeat the steps that previously triggered the "assert" it now works as expected. Great! I'm just a user rather than a developer so I'll leave it to you guys to decide when to close it, but it certainly looks fixed to me!

**Comment by hodoulp** [comment] 2021-05-12 15:13
@df-0, @fnordware, Can that issue be closed now that all related pull requests are merged?

**Comment by df-0** [comment] 2021-05-12 15:48
> @df-0, @fnordware, Can that issue be closed now that all related pull requests are merged?

As I mentioned, I'm not a developer, just a user, so I'm afraid I'm not really qualified to answer that! I would defer to @fnordware

**Comment by fnordware** [comment] 2021-05-12 16:16
Yes, close it! Thanks again, @df-0.

**Closed** 2021-05-12 16:22 UTC
