### ISSUE TITLE
Unit tests fail in some windows machines after adding Imath 3 support for half dependency

### ISSUE THREAD

**Issue by ansono** [AcademySoftwareFoundation/OpenColorIO#1590] opened 2022-01-20 09:13 UTC
After a bisection we discovered that in some windows machines the unit tests were failing after https://github.com/AcademySoftwareFoundation/OpenColorIO/commit/ea4300aeb9af58d694c0bb408680f12950bd6c7e, where it started using Imath 3 by default.

If we switch to OpenEXR with `-DOCIO_USE_OPENEXR_HALF=ON`, the unit tests pass.

**Comment by hodoulp** [comment] 2022-01-20 13:54
**[Windows Only]** We were unable to reproduce it on any local machines, and did not see any Windows CI machine differences for now (on some Windows CI machines it works, and fails for others).

Below are compilation details:
```
- cmake -G "Visual Studio 16 2019" -Dyaml-cpp_STATIC_LIBRARY="ON" -DOCIO_BUILD_DOCS="OFF" -DCMAKE_MSVC_RUNTIME_LIBRARY="MultiThreadedDLL" -DCMAKE_C_FLAGS="/O2 /Gy /GS- /Oy /GR /EHsc /D_ITERATOR_DEBUG_LEVEL=0 -d2FH4- -DWIN32" -DCMAKE_CXX_STANDARD_REQUIRED="ON" -DCMAKE_CXX_FLAGS="/O2 /Gy /GS- /Oy /GR /EHsc /D_ITERATOR_DEBUG_LEVEL=0 -d2FH4- -DWIN32" -DOCIO_BUILD_JAVA="OFF" -DCMAKE_EXE_LINKER_FLAGS="-d2:-FH4-" -DCMAKE_POSITION_INDEPENDENT_CODE="TRUE" -DCMAKE_POLICY_DEFAULT_CMP0091="NEW" -DCMAKE_INSTALL_PREFIX="[INSTALL_FOLDER]" -DOCIO_BUILD_PYTHON="OFF" -DBUILD_SHARED_LIBS="OFF" -DHalf_STATIC_LIBRARY="ON" -Dexpat_STATIC_LIBRARY="ON" -DOCIO_BUILD_TESTS="ON" -DOCIO_BUILD_APPS="OFF" -DOCIO_BUILD_GPU_TESTS="OFF" -DCMAKE_BUILD_TYPE="Release" -Dpystring_STATIC_LIBRARY="ON" -DCMAKE_CXX_EXTENSIONS="OFF" -DHalf_ROOT="s:\temp\arnold-kook\openexr\install\openexr-2.4.0_static_windows_vc-14.2_cxx14" -DCMAKE_POLICY_DEFAULT_CMP0074="NEW" -DOCIO_BUILD_NUKE="OFF" -DCMAKE_CXX_STANDARD="14" ..
- msbuild /m /p:Configuration=Release /p:Platform=x64 ALL_BUILD.vcxproj
```

Few more notes:
- All unit tests using `half` LUTs fail.
- `half / openexr` flags are discarded as the build defaults to `Imath` (which is downloading version 3.1.2).
- compilation generates a static library and only consumes static libraries for the third-party dependencies (i.e. `yaml-cpp`, `expat`, `pystring` and `Imath`) so, it should be independent from system libraries.

**Comment by hodoulp** [comment] 2022-01-20 14:21
When running the OpenColorIO unit tests, below is the most basic failure:
```
- OCIO::Lut1DOpData l2(OCIO::Lut1DOpData::LUT_INPUT_HALF_CODE, 65536, false);
- OCIO_CHECK_ASSERT(l2.isIdentity());
```

**Comment by doug-walker** [comment] 2022-04-22 00:50
Closing this as we were not able to reproduce the issue.

**Closed by doug-walker** 2022-04-22 00:50 UTC
