### ISSUE TITLE
Blender: Error using OCIO with AgX Color Space on Apple Silicon

### ISSUE THREAD

**Issue by berenyiaustin** [AcademySoftwareFoundation/OpenColorIO#1810] opened 2023-06-28 19:25 UTC
Below I have renders in all 11 Look options for the EaryChow fork of AgX. It seems that Very High Contrast, High Contrast, Medium High Contrast, Medium Low Contrast, Low Contrast, and Very Low Contrast are all producing identical results. Nothing changes when switching between those looks.

None
<img width="592" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/18562453/fe7f179e-7eb2-47b4-bf45-28d891874e10">

Punchy
<img width="592" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/18562453/d2ef68aa-7c93-45e8-9cc8-809a04af52ba">

Green Ink
<img width="592" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/18562453/b333ef8f-938f-467b-86b5-6803dbe53507">

Greyscale
<img width="592" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/18562453/34881bc8-9396-4201-b446-a5815fb1fdfa">

Very High Contrast
<img width="592" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/18562453/8f66bc45-8d8a-4719-a799-551058f397b0">

High Contrast
<img width="592" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/18562453/86c504ac-aa71-433b-a251-a8a89ca49452">

Medium High Contrast
<img width="592" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/18562453/0e4a3339-d465-4163-ad30-f13cd6346091">

Base Contrast
<img width="592" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/18562453/84c9880b-a8dc-4c9a-9b80-22ba6c6352c4">

Medium Low Contrast
<img width="592" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/18562453/5316fd8e-c3fc-4d20-8223-0084f4cda76b">

Low Contrast
<img width="592" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/18562453/18544f2a-b22d-4a0f-ac49-83c461bd09b2">

Very Low Contrast
<img width="592" alt="image" src="https://github.com/AcademySoftwareFoundation/OpenColorIO/assets/18562453/fc9b2bcd-cc37-439c-aa89-84ab9fb59e95">

I also receive the following error when changing Look:

> Compile Error - Metal Shader Library (Stage: 2), error Error Domain=MTLLibraryErrorDomain Code=3 "program_source:2310:10: error: value of type 'bool attribute((ext_vector_type(3)))' (vector of 3 'bool' values) is not contextually convertible to 'bool'
> if ( gamma != vec3(1., 1., 1.) )
> ^~~~~~~~~~~~~~~~~~~~~~~~~
> " UserInfo={NSLocalizedDescription=program_source:2310:10: error: value of type 'bool attribute((ext_vector_type(3)))' (vector of 3 'bool' values) is not contextually convertible to 'bool'
> if ( gamma != vec3(1., 1., 1.) )
> ^~~~~~~~~~~~~~~~~~~~~~~~~
> }

Display Device: sRGB
View Transform: AgX

Blender 4.0a, MacOS Apple Silicon, Metal Backend

**Comment by EaryChow** [comment] 2023-07-02 21:10
Just to fill in some context, the contrast looks in question were using `GradingPrimaryTransform`, and it's reported to my fork of AgX that it throws shader error in MacOS, I had them try out [the test config for the `GradingPrimaryTransform` shader error bug](https://github.com/sobotka/AgX/tree/grading-primary-config) and they confirmed it also throws error. Therefore I suspect there is a bug unresolved in OCIO upstream that throws error when using Grading Primary Transform on MacOS, since I remember [some similar issue](https://github.com/AcademySoftwareFoundation/OpenColorIO/issues/1603) was brought up before, and I thought it was fixed.

**Comment by EaryChow** [comment] 2023-07-06 22:55
@doug-walker Any hope of confirming and fixing this? Maybe this issue needs to be renamed to "Grading Primary Tramsform having Compile Error on Metal Shader Library", to clear the confusion.

**Comment by remia** [comment] 2023-07-10 20:00
@EaryChow I'm not able to reproduce the issue on OCIO upstream (main branch), do you have a simple way to test? I used `ociodisplay -v -gpuinfo -metal` on the AgX config you shared above and selected the Look to test the bug but no error happened.

The shader error from the first post seem to indicate that version of Blender is using a version before the bug was fixed, in the newer versions the line conditional test is now: `if ( any( gamma != float3(1., 1., 1.) ) )`.

Happy to investigate if there is a way to reproduce on the last releases of 2.1.x or 2.2.x, I don't think 2.0.x got the fix however.

**Comment by EaryChow** [comment] 2023-07-10 20:03
Thanks, good to know the bug is already fixed upstream. Maybe now we need to investigate the downstream.

**Comment by remia** [comment] 2023-07-10 20:07
From a quick search, I think this was fixed in 2.1.1+ and 2.2.0+.

**Comment by EaryChow** [comment] 2023-08-29 07:54
It turned out to be Blender using GLSL causing the problem, [now fixed](https://projects.blender.org/blender/blender/commit/259bfc45534af90a4d2b0a3d92a763114bb0ff22)

**Closed** 2024-05-15 00:10 UTC
Labels: Support, To Close
