### ISSUE TITLE
Move binaries which depend on OpenImageIO to the OIIO project

### ISSUE THREAD

**Issue by darix** [AcademySoftwareFoundation/OpenColorIO#1484] opened 2021-09-07 14:00 UTC
Right now you have a build cycle between those OCIO and OIIO, moving the 4 tools depending on OIIO over to that project would resolve this cycle.

Is there any reason why those tools should live here?

**Comment by KelSolaar** [comment] 2021-09-07 18:54
Hi @darix,

This issue is a duplicate of #1233.

**Closed** 2021-09-07 19:22 UTC
